# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanager', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
