# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanager', '0003_course_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Users',
        ),
        migrations.AddField(
            model_name='course',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='Courses_that_are_liked', to='coursemanager.User'),
        ),
    ]
