# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanager', '0004_auto_20180222_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Course')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.User')),
            ],
        ),
    ]
